export const DB_NAME = 'cohand';
export const DB_VERSION = 2;
export const MAX_STATE_SIZE = 1024 * 1024; // 1MB
export const MAX_TEXT_CONTENT_LENGTH = 500;
export const MAX_CUMULATIVE_READS = 50 * 1024; // 50KB
export const MAX_NOTIFICATIONS_PER_TASK_PER_HOUR = 10;
export const MAX_SCRIPT_VERSIONS = 10;
export const MAX_RUNS_PER_TASK = 100;
export const QUICKJS_MEMORY_LIMIT = 32 * 1024 * 1024; // 32MB
export const QUICKJS_TIMEOUT_MS = 5 * 60 * 1000; // 5 min
export const QUICKJS_MODULE_POOL_SIZE = 3;
export const RPC_TIMEOUT_MS = 60_000; // 60s per RPC
export const HUMANIZE_ACTIONS_PER_HOUR = 15;
export const REPAIR_BUDGET = 2;
export const WEBSOCKET_PORT = 19988;
export const MAX_STATE_SNAPSHOTS_PER_TASK = 10;
export const LLM_USAGE_RETENTION_DAYS = 90;
export const NAVIGATOR_RATE_LIMIT = 5; // per minute
export const NAVIGATOR_PERMISSION_EXPIRY_DAYS = 30;
export const MAX_PAGE_SNAPSHOTS = 20;
export const MAX_SNAPSHOT_SIZE = 50 * 1024; // 50KB
export const MAX_A11Y_DEPTH = 5;
export const CLICK_DEDUP_MS = 300;
export const SPEECH_ASSOCIATION_WINDOW_MS = 3000;
export const OAUTH_RULE_ID = 99999;
export const OAUTH_RULE_CHECK_INTERVAL_MS = 30_000;
export const OAUTH_RULE_MAX_LIFETIME_MS = 5 * 60 * 1000;
export const CODEX_CLIENT_ID = 'app_EMoamEEZ73f0CkXaXp7hrann';
export const CODEX_REDIRECT_URI = 'http://localhost:1455/auth/callback';
export const CODEX_AUTH_URL = 'https://auth.openai.com/oauth/authorize';
export const CODEX_TOKEN_URL = 'https://auth.openai.com/oauth/token';
