export const DB_NAME = 'cohand';
export const DB_VERSION = 1;
export const MAX_STATE_SIZE = 1024 * 1024; // 1MB
export const MAX_TEXT_CONTENT_LENGTH = 500;
export const MAX_CUMULATIVE_READS = 50 * 1024; // 50KB
export const MAX_NOTIFICATIONS_PER_TASK_PER_HOUR = 10;
export const MAX_SCRIPT_VERSIONS = 10;
export const MAX_RUNS_PER_TASK = 100;
export const QUICKJS_MEMORY_LIMIT = 32 * 1024 * 1024; // 32MB
export const QUICKJS_TIMEOUT_MS = 5 * 60 * 1000; // 5 min
export const QUICKJS_MODULE_POOL_SIZE = 3;
export const RPC_TIMEOUT_MS = 60_000; // 60s per RPC
export const HUMANIZE_ACTIONS_PER_HOUR = 15;
export const REPAIR_BUDGET = 2;
export const WEBSOCKET_PORT = 19988;
export const MAX_STATE_SNAPSHOTS_PER_TASK = 10;
export const LLM_USAGE_RETENTION_DAYS = 90;
export const NAVIGATOR_RATE_LIMIT = 5; // per minute
export const NAVIGATOR_PERMISSION_EXPIRY_DAYS = 30;
